### ISSUE TITLE
PBI 1: Setup Database

### ISSUE THREAD

**Issue by abhagat8** [COSC481W-2024Fall/Swoop-In#1]
**User Story**
john who wants to use the Swoop-in app will need a place to store there data like there likes, chats, and settings. that is why we want to setup a database for all the information to be held for John. the resources we will need for this issue is to use MongoDB and Firebase.

**Persona**: John who is using the Swoop-in application and needs to store information. he has many people that like him so he needs the app to be able to remember all the information related to him
**Feature:** To hold information related to the user in MongoDB and Firebase.
**Business Value:** This allows user to save information when they leave the app. this allows them to save chats, likes and preferences.

**Task:** 

- [x] config MongoDB 
- [x] setup relational schema for the mongo
- [x] config firebase database
- [x] setup relational schema for firebase 
- [x] have mongo database handle the user matching 
- [x] have firebase database hold information for login and other user information 
- [x] have the firebase database be able to take in information from login page.

**Acceptance Criteria**

1. mongo has to be able to make insert, retrieve, update, and delete  calls
2. firebase has to be able to make insert, retrieve, update, and delete calls
3. If user makes an account with Swoop-in, the firebase will hold information for user email and password.
4. if user has preferences of matches, the mongo will hold the information.
