### ISSUE TITLE
PBI 5: Making Settings page

### ISSUE THREAD

**Issue by abhagat8** [COSC481W-2024Fall/Swoop-In#10]
**User Story:** 
John is user of Swoop-in and he wants a page in the app that will let him see all his settings. He wants to be able to customize his app and some of the features the app  offers like editing password, notifications, light mode, and blocklist. This page will act as a place user can come to edit settings for the app. 

**Persona:** John is user of Swoop-in and he wants a place where he can edit his settings in the app. 
**Feature:** Make a UI for the settings page which will allow the user to edit settings for the app like passwords, notifications, light mode, and blocklist
**Business Value:** This allows the user of the app to customize parts of the application, and improve user satisfaction. 

**Tasks:**
- [x] Create UI page that displays all the Settings options 
- [x] Create an option to edit Email or password
- [x] Create an option to edit notifications preference
- [x] Create an option to edit light mode preference
- [ ] Create an option to add or remove user from blocklist
- [ ] Add location in database that can hold information for settings options
- [ ] Check all of settings are able to communicate with the database.   

**Acceptance Criteria:** 
1. The user can go to the settings page and see all settings options
2. The user can edit all the settings options 
3. The edits the user makes is saved in the database

**Comment by sjiang1** [comment]
1. Please add a label, "sprint-2"
2. Do you need to wait for the database setup for settings' options? Who will be responsible for that?
3. Please double check your timeline (start date and end date on this issue)
