### ISSUE TITLE
PBI 6: Add Chat Feature

### ISSUE THREAD

**Issue by RamiDari15** [COSC481W-2024Fall/Swoop-In#11]
**User Story:** 
Jerry is a user of Swoop-in and he wants a page in the app that will let him chat with the people. who matched with him asnd the people who swiped right on him. He wants to be able to chat with people to lead from of the chat. 

**Persona:** Jerry is user of Swoop-in and he wants a place where he can chat with people. 
**Feature:** Make a UI for the chat page which will allow the user to chat with the people who he matched and swipe on.
**Business Value:** This allows the user of the app to chat with other people and improve user satisfaction. 

**Tasks:**
- [ ] Create UI page that show a mnessage chat page
- [ ] Create the ability to message people who they matched with
- [ ] Create the ability to message people who they swiped on them
- [ ] Create an option to clear chats
- [ ] Create an option to block users

**Acceptance Criteria:** 
1. The user can go to the message page and see all messaging log
2. The user can send messages

**Comment by sjiang1** [comment]
1. The title of this PBI is missing
2. The screenshot of this PBI misses the title with the issue ID number
3. Make sure you add testing for this PBI (not manual testing)
4. Add a label for this issue "sprint-2"
5. Double check the start and end date on this issue page

**Comment by sjiang1** [comment]
Also, this PBI was not on the GitHub project board (I added it.). In the future, please make sure to add the PBIs to the project board.
