### ISSUE TITLE
PBI 2: Make UI for Main Page

### ISSUE THREAD

**Issue by abhagat8** [COSC481W-2024Fall/Swoop-In#2]
**User Story:**
John is a new user for Swoop-in, he wants a page where he is able to have a spot in the app where he can see the new people he can connect, and be able to navigate to other parts of the app. This page in the application will  act like the home page where john will be directed to when he logs in. 

**Persona:** John is a new user to Swoop-in and would like to have a page where he can connect with other people that will act like a home page.
**Feature:** have a UI page that will allow user to see people they can connect with, and a tool bar that will help then go to other parts of the app.
**Business Value:** Users will have a central place where they can connect to new people and be able to easily navigate the app

**Tasks**
- [ ] Create UI page that displays a carousel that displays the images from users with buttons that cycle
- [ ] Create a biography section and a name section beneath carousel
- [ ] Create a navbar at bottom with home button, match button, chat button, and profile button and top settings button that navigates to associated page
- [ ] Create a like and dislike button beneath the carousel
- [ ] Create tests to make sure everything is displayed properly and in a user friendly way.
- [ ] Merge the main to my branch to make sure it is cohesive.

**Acceptance Criteria**
1. User should be able to cycle through carousel with associated buttons
2. Pictures should populate the carousel
3. User should be able to see name and biography
4. When pressing buttons, user should be redirected to associated pages (empty)
5. User should be able to interact with like and dislike button beneath carousel
