### ISSUE TITLE
PBI 9 - Fix Dark/Light mode and status showing

### ISSUE THREAD

**Issue by linchristina03** [COSC481W-2024Fall/Swoop-In#27]
**User Story:** 
John wants to use the application in Dark mode. right now the app only does dark mode for settings page. John would like dark mode or light mode to be applied to all pages. John also wants to know when he can message other users and when they are active on the app. Right now he does not know when his friends are online so he can message them. John would like to know the status of his matches so he can talk to them.

**Persona**: John is a user of Swoop-in and he wants to be able to enable dark mode or light mode across all pages in app. John also want to be able to see the status of when his matches are online. 
**Feature**: Develop code that will enable dark mode or light mode for all pages and develop code that will add a feature that shows the active status for users.
**Business Value**: by enabling dark mode and light mode we are polishing our app which should improve user experience. while add a status feature will give the user the ability to know when there matches are online so they can interact better.

**Tasks:** 

- [ ] develop code for all our pages that will check if our dark mode setting is enabled in database
- [ ] if the setting is enabled then the code has to change the theme of the page accordingly.
- [ ] create test to confirm all pages changes the theme and no mismatches happen
- [ ] edit database to hold a settings for if the user want to show there status or not
- [ ] develop code to show user when there matches were last online or if they are online
- [ ] create test to confirm that status information is accurate.

**Acceptance Criteria:** 

1. If the user enables dark mode in setting ALL pages change theme to dark, same for light mode
2. the user can look at his matches and have a way to see if that user is online or when they were last online
