### ISSUE TITLE
PBI 3: Make UI for Login Page

### ISSUE THREAD

**Issue by abhagat8** [COSC481W-2024Fall/Swoop-In#3]
**User Story:** 
John wants to became a new user for our application. he needs to be able to have a page where he can log into our application with his emich email and password. 

- **Persona:** John who is new to Swoop-in and wants to log into the application

- **Feature:** make a UI for a page that will allow user to enter user name and an emich email to use to log into the swoopin application. 

- **Business Value:** this allows the application to have new user to log in and it also helps with security for the users too as you need to enter password. 

**Tasks**
- [ ] Create UI page that displays a greeting message
- [ ] Create Text boxes to enter the user name and password
- [ ] create a link/button to register/signup
- [ ] create a link/button to reset password
- [ ] create a link/button for a help page
- [ ] create a login button to authenticate user information.
- [ ] create tests to make sure everything is displayed properly and in a user friendly way.
- [ ] merge the main to my branch to make sure it is cohesive.

**Acceptance Criteria**
1. If the user launches the page, the page should display the login page when the site launches.
2. If the user clicks on the textbox, the user will be able to fill in their log in information.
3. Sign-in process and password storage follows industry standards
4. If the user clicks the login button it will authenticate and the user will be logged in and view the home page.
5. If the user clicks the login button with either textbox empty a pop-up message will display with the error.
6. If the user information is incorrect a pop-up message will display with the error.
