### ISSUE TITLE
PBI 4: Authorization for Login page

### ISSUE THREAD

**Issue by abhagat8** [COSC481W-2024Fall/Swoop-In#4]
**User Story:** 
John is a EMU student who wants to be use Swoop-in. John however wants to only meet new people that are in EMU. the Swoop-in app needs to only allow Emich people to make a new account with the application 

**Persona:** John is a EMU student and wants to only meet people from only EMU.
**Feature:** to have an authorization system that will only allows user with valid emich emails to make an account 
**Business Value:** this adds a layer of security so the scoop of the application is only within Swoop-in.

**Tasks**
- [ ] Create Login functionality with email and password
- [ ] Ensure the emails are emich
- [ ] Connect page with firebase
- [ ] Ensure functionailty for login works
- [ ] Add to firebase when a new user logs in

**Acceptance Criteria**
1. If the user creates an account must be with emich email
2. If the user login with correct informations the firebase authenticates it and redirect to main page
3.  Logs in doesn't direct to main page if login information is not correct
